# Generated by Django 4.2.30 on 2026-10-09 19:02

import django.core.validators
from django.db import migrations, models
import servicios.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='archivo',
            field=models.FileField(upload_to='evidencias/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp']), servicios.models.validar_tamano_evidencia]),
        ),
    ]
