# Generated by Django 5.2.17 on 2026-09-28 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Director')),
                ('nacionalidad', models.CharField(blank=True, default='', max_length=80, verbose_name='Nacionalidad')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
                'db_table': 'directores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Género')),
                ('descripcion', models.CharField(blank=True, default='', max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'db_table': 'generos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año de estreno')),
                ('duracion', models.PositiveSmallIntegerField(default=90, verbose_name='Duración (minutos)')),
                ('clasificacion', models.CharField(choices=[('TE', 'Todo espectador'), ('TE7', 'Mayores de 7'), ('14', 'Mayores de 14'), ('18', 'Mayores de 18')], default='TE', max_length=3, verbose_name='Clasificación')),
                ('precio_arriendo', models.PositiveIntegerField(default=2500, verbose_name='Precio de arriendo')),
                ('stock', models.PositiveSmallIntegerField(default=1, verbose_name='Copias disponibles')),
                ('sinopsis', models.TextField(blank=True, default='', verbose_name='Sinopsis')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogoApp.director', verbose_name='Director')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogoApp.genero', verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'db_table': 'peliculas',
                'ordering': ['titulo'],
            },
        ),
    ]
