# Generated by Django 5.2.17 on 2026-09-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('cargo', models.CharField(max_length=120)),
                ('periodo', models.CharField(max_length=30)),
                ('resena', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['cargo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, unique=True)),
                ('comuna', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('fundacion', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
            ],
        ),
    ]
