# Generated by Django 5.2.17 on 2026-09-28 16:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=12, unique=True, verbose_name='RUN')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('materno', models.CharField(blank=True, default='', max_length=100, verbose_name='Apellido Materno')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('fecha_registro', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Cliente activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['paterno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_arriendo', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de arriendo')),
                ('fecha_limite', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha límite de devolución')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de devolución')),
                ('estado', models.CharField(choices=[('A', 'Arrendada'), ('D', 'Devuelta'), ('R', 'Atrasada')], default='A', max_length=1, verbose_name='Estado')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total a pagar')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogoApp.pelicula', verbose_name='Película')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clientesApp.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Arriendo',
                'verbose_name_plural': 'Arriendos',
                'db_table': 'arriendos',
                'ordering': ['-fecha_arriendo', '-id'],
            },
        ),
    ]
